// src/modules/course/domain/entities/category.entity.ts

export class Category {
  private _id: number = 0
  private _uuid: string = ''
  private _name: string = ''
  private _createdAt: Date = new Date()
  private _updatedAt: Date = new Date()

  constructor(
    id: number, 
    uuid: string, 
    name: string, 
    createdAt: Date, 
    updatedAt: Date
  ) {
    this._id = id
    this._uuid = uuid
    this.setName(name)
    this._createdAt = createdAt
    this._updatedAt = updatedAt
  }

  get id() {
    return this._id
  }

  get uuid() {
    return this._uuid
  }

  get name() {
    return this._name
  }

  get createdAt() {
    return this._createdAt
  }

  get updatedAt() {
    return this._updatedAt
  }

  // ---------------- Business Rules ----------------
  setName(name: string) {
    if (!name || name.trim() === '') {
      throw new Error('Category name cannot be empty')
    }
    
    if (name.length > 100) {
      throw new Error('Category name cannot exceed 100 characters')
    }
    
    this._name = name.trim()
  }

  rename(newName: string) {
    this.setName(newName)
    this._updatedAt = new Date()
  }

  // Helper method to update entity
  update(data: Partial<{ name: string }>) {
    if (data.name !== undefined) {
      this.setName(data.name)
    }
    this._updatedAt = new Date()
  }

  // Static factory method
  static create(name: string): Category {
    const now = new Date()
    return new Category(
      0, // id will be set by database
      '', // uuid will be generated by database
      name,
      now,
      now
    )
  }

  // Convert to plain object (optional, for serialization)
  toJSON() {
    return {
      id: this._id,
      uuid: this._uuid,
      name: this._name,
      createdAt: this._createdAt,
      updatedAt: this._updatedAt
    }
  }
}